services:
  - type: web
    name: circlex-backend
    env: python
    plan: free

    runtime: python-3.10.13   # ✅ ADD THIS LINE

    rootDir: .

    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
